name: docker-compose-actions-workflow
on:
  push:
    branches:
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: making ssh dir
        run: sudo mkdir ~/.ssh
      - name: making known_hosts file
        run: sudo touch ~/.ssh/known_hosts
      - name: Known hosts
        run: sudo echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - name: Copying to remote
        run: sshpass -p '37!T4nPP6' rsync -avz ./dist/ ubuntu-1027223@145.24.222.85:/home/ubuntu-1027223/projectc/dist/
